chart/tests/carto.yaml, chart/tests/chart-values.yaml, chart/tests/goss/goss-accounts-www/goss.yaml
First goss tests for 'accounts-www' pods
**Benefits**
Now it is possible to detect regressions that could affect to 'accounts-www' component. Also there is a dir structure that will keep goss tests separated per Carto's component.
=> Goss tests for accounts-www

chart/Chart.lock, chart/Chart.yaml, chart/README.md, chart/templates/NOTES.txt, chart/templates/_helpers.tpl, chart/templates/import-api/deployment.yaml, chart/values.yaml
Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>
BREAKING CHANGE: This PR bumps the PostgreSQL subchart to 11.x.x and Redis to 16.x.x. It also changes the PostgreSQL container version to branch 13. The values have been adapted and unnecessary checks have been removed.
**Benefits**
New features
Users will need to adapt their values.yaml file in case they were using the Redis and PostgreSQL subcharts. They will also need to change the PostgreSQL version.
- fixes #
=> feat!: :arrow_up: Bump PostgreSQL and Redis subchart major version

chart/templates/import-api/configmap.yaml, chart/templates/maps-api/configmap.yaml
- Fix error 401 while trying to load queries from DW or connections.
- Tested imports and queries to all the supported DBs and DW.
=> fix error 401 in maps & import

chart/templates/externalredis-secret.yaml
Redis secret template has a typo
**Benefits**
APIs cannot connect to Redis because of this
None
None
None
=> Fix Redis credentials secret

.github/workflows/vib.yaml, .vib/carto/cypress/cypress.json, .vib/carto/cypress/cypress/integration/carto_spec.js, .vib/carto/cypress/cypress/plugins/index.js, .vib/carto/cypress/cypress/support/commands.js, .vib/carto/cypress/cypress/support/index.js, .vib/carto/goss/goss-accounts-www/goss.yaml, .vib/vib-pipeline.json, .vib/vib-platform-verify.json
- Added Cypress action and a simple test to be run by VIB.
- Modified the current deployment configuration to deploy the chart using custom values so that no containers need to be disabled. 
- A bigger instance is now used to avoid resource issues.
- Updated `TARGET_PLATFORM` env name to the new naming scheme to avoid [future issues](https://github.com/vmware-labs/vmware-image-builder-action/blob/main/src/main.ts#L491).
-  Fixed listening port used in Goos tests per https://github.com/CartoDB/carto-selfhosted-helm/pull/28
- Modified trivy's action threshold to avoid false negatives.
**Benefits**
The verification pipeline now supports functional testing via Cypress.
As the PR modifies GitHub's VIB workflow the changes fail unless …
=> Add Cypress tests for VIB action

chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/35232d8481552562c7f5b9179c7739a7b38078a3
=> Update to `1.15.1` release

.github/workflows/vib.yaml
Excludes Markdown `*.md` files for them not to trigger the VIB action.
**Benefits**
Avoid unnecessary Infrastructure resources and achieves shorter testing times for those PRs only modifying `*.md` files.
**Additional Information**
Workflow change tested in https://github.com/FraPazGal/carto-selfhosted-helm/pull/3
=> Exclude Markdown files to not trigger VIB

chart/README.md, chart/templates/_helpers.tpl, chart/templates/accounts-www/deployment.yaml, chart/templates/cdn-invalidator-sub/deployment.yaml, chart/templates/http-cache/deployment.yaml, chart/templates/import-api/deployment.yaml, chart/templates/import-worker/deployment.yaml, chart/templates/lds-api/deployment.yaml, chart/templates/maps-api/deployment.yaml, chart/templates/router/deployment.yaml, chart/templates/workspace-api/deployment.yaml, chart/templates/workspace-subscriber/deployment.yaml, chart/templates/workspace-www/deployment.yaml, chart/values.yaml
Now the Docker image name it's split into 2 different values
```yaml
workspaceApi:
registry: gcr.io/carto-onprem-artifacts
repository: workspace-www
```
You can also specify the image tag for only 1 component
```yaml
workspaceApi:
tag: latest
```
**Benefits**
More user-friendly :)
- fixes #
=> Refactor Docker images templating

chart/templates/_helpers.tpl, chart/templates/cdn-invalidator-sub/deployment.yaml, chart/templates/import-api/configmap.yaml, chart/templates/import-api/deployment.yaml, chart/templates/import-worker/configmap.yaml, chart/templates/import-worker/deployment.yaml, chart/templates/lds-api/deployment.yaml, chart/templates/workspace-api/configmap.yaml, chart/templates/workspace-api/deployment.yaml
- Fix command cdn-invalidator-sub
- Fix gcp-secrets mounted in cdn-invalidator-sub
**Benefits**
- fixes #
=> Multiple fixes from RT review

chart/templates/cdn-invalidator-sub/deployment.yaml, chart/templates/import-worker/deployment.yaml, chart/templates/workspace-subscriber/deployment.yaml
The idea is that if you execute helm install carto from the official helm repo (without any customer file) all pods were able to run without restarts, `import-worker`, `workspace-subscriber` and `cnd-invalidator` needs these tenant config params, in other case they will be restarting continually. The rests of the components do not need this params to stay in running state.
This is a prerequisite in some marketplaces to publish the chart
**Benefits**
- fixes #
=> feat(chart): scale 0 replicas if tenant info value is missing

chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/10c7ac3a4e71203b58d25328e38d47dc091199e1
=> Update to `1.21.2-2022.04.04` release

chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/14799296f56b49cd1e7d156d8f555137c63abcae
=> Update to `1.21.6-2022.05.05` release

.github/workflows/vib.yaml
Signed-off-by: FraPazGal <fdepaz@vmware.com>
We should avoid using the `main` branch of the VIB action, which can be subjected to faulty code. Changing the action version to a fixed release reduces the risk.
This PR changes the `vmware-labs/vmware-image-builder-action` action to its latest release per the [GH's marketplace](https://github.com/marketplace/actions/vmware-image-builder).
**Benefits**
Stability increase for the VIB action.
We'll need to manually update the used version whenever there is a new release.
=> Use stable version for VIB action

chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/557a78afe4067a053f526af88d4bb4e6ab8aec03
=> Update to `1.23.5-2022.5.30` release

chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/9f097ed5908572e2f0af140db6d888848f75149d
=> Update to `1.23.8-2022.6.2` release

chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/ab503135539cce706f8514a6d067b4b4850d8a1e
=> Update to `1.24.2-2022.6.6` release

chart/templates/pre-upgrade-check-versions-job.yaml
In order to align pre-hook check with customer package file we need to change 
**Benefits**
Upgrade will be safe
**Related Shorcut Story**
https://app.shortcut.com/cartoteam/story/229372/perform-selfhosted-version-check-at-installation-time
=> FIX: Change version parameter name

chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/1c39ecbd71518478555b9deddd40560c5a301fa9
=> Update to `1.25.2-2022.6.8-3` release

chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/4c738da8b0224cea823316c3b6799f6b8d075fbd
=> Update to `1.26.2-2022.6.10-1` release

chart/templates/http-cache/configmap.yaml, chart/values.yaml
https://app.shortcut.com/cartoteam/story/219532/adjust-varnish-to-docker-kubernetes#activity-237384
- Adjusting varnish resources
- Dynamically setting `VARNISH_SIZE` (`malloc`) depending on the value configured in `resources.requests.memory` 
With these new settings:
- `resources.limits.memory` = 2048M
- `resources.requests.memory` = 1256M
- `VARNISH_SIZE` (`varnish malloc`) = `resources.requests.memory` * 3 / 4 = 942M
(75%, leaving a margin of 25% for fragmentation, overhead, etc as recommended in the docs)
In case the `resources.requests.memory` is absent, varnish will run with its default value for malloc, which will be `256M` once [this PR](https://github.com/CartoDB/cloud-native/pull/7678) is merged.
With the following values:
```
httpCache:
resources:
limits:
memory: "2048Mi"
cpu: …
```
=> adjust varnish resources

chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/c6804eb05923e31ba59585b475efd70e32fe099b
=> Update to `1.28.1-2022.6.21` release

CHANGELOG.md, chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/d3758dcd029211fd1d5a4b8f75c17d4b9f687a5c
=> Update to `1.34.1-2022.6.29` release

CHANGELOG.md, chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/9c5e87c08b6ce69ab1e81be05756a66bbb1ff28c
=> Update to `1.35.2-2022.7.1` release

CHANGELOG.md, chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/1f6c6ba19c4e829bccea6f3a999e9d70806911ff
=> Update to `1.35.4-2022.7.5-1` release

CHANGELOG.md, chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/ab5ec39d60facfc71c8416fc846d343a628dcfd7
=> Update to `1.38.4-2022.7.20` release

chart/templates/carto-common-service-account.yaml, doc/gke/gke-workload-identity.md
The value `commonBackendServiceAccount.create` is not mapped with the related resource. There is a conflict If we disable commonBackendServiceAccount creation  and we want to use enableGCPWorkloadIdentity. We have added a warning in the documentation
**Benefits**
Users can deactivate the creation of k8s service account
Workload identity will not work if commonBackendServiceAccount.create is false
=> fix commonBackendServiceAccount create condition

CHANGELOG.md, chart/Chart.lock, chart/Chart.yaml
- https://github.com/CartoDB/cloud-native/commit/d5eda43e7b930dd127e81b4049a954ac7e43453a
=> Update to `1.39.1-2022.8.1` release

chart/templates/lds-api/configmap.yaml
https://app.shortcut.com/cartoteam/story/250586/pubsub-project-id-env-var-is-missing-in-selfhosted-lds-api-configmap
- Add missing pubsub project id env var to LDS-API configmap
**Benefits**
- Fix bug in LDS-API
- fixes #
=> Add pubsub project to lds configmap

chart/README.md, chart/templates/accounts-www/configmap.yaml, chart/templates/workspace-www/configmap.yaml, chart/values.yaml, customizations/README.md
- Add WORKSPACE_THUMBNAILS_BUCKET env var to www config maps
- Relates to https://github.com/CartoDB/cloud-native/pull/8781
**Benefits**
- We need this env var to generate dynamically the csp and nginx configs
- fixes #
=> breaking change: Add thumbnailsBucketExternalURL var to www configs

chart/templates/sql-worker/configmap.yaml
Fix duplicate key error.
**Benefits**
Fixing the broken.
None.
=> Remove duplicate PUBSUB_PROJECT_ID key from sql-worker cm

customizations/README.md, customizations/ingress/gke/custom_cert_config.yaml, customizations/ingress/gke/gcp_managed_cert_config.yaml
Added comments to the ingress/gke example to include 
`cloud.google.com/neg: '{"ingress": true}'`
**Benefits**
Cover the case were container native load balancing is not default
=> Add-neg-config-to-ingress-example

chart/README.md, chart/templates/router/service.yaml, chart/values.yaml, customizations/README.md, customizations/service_loadBalancer/aws_eks_tls_offloading/config.yaml
Modified service template and values.yaml to mek configurable the target por for tls offloading cases.
Add an example config for TLS Offloading with AWS ELBs (network load balancing) using ACM certificates
**Benefits**
Now uses have a template to configure external connection with EKS + TLS Offloadings without ingress, just with a network load balancer
- fixes #
You need to upload your certificate (or generate one ) in AWS ACM 
https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html
AWS ELB gives you an dns domain name that need to be configured as CNAME of yourt SH domain.
=> Add TLS offloading on AWS LB

README.md, doc/whitelisted_domains
https://app.shortcut.com/cartoteam/story/267124/monitor-egress-traffic-from-selfhosted-gke-pods
=> add whitelisted domains

chart/templates/maps-api/configmap.yaml, chart/templates/maps-api/deployment.yaml, chart/templates/maps-api/secret.yaml
- The BQ Oauth connection client id and secret need to be propagated to maps-api component
=> add missing variables to maps-api

.gitignore, chart/README.md, chart/templates/_helpers.tpl, chart/templates/cdn-invalidator-sub/configmap.yaml, chart/templates/cdn-invalidator-sub/deployment.yaml, chart/templates/externalproxy-configmap.yaml, chart/templates/import-api/configmap.yaml, chart/templates/import-api/deployment.yaml, chart/templates/import-worker/configmap.yaml, chart/templates/import-worker/deployment.yaml, chart/templates/lds-api/configmap.yaml, chart/templates/lds-api/deployment.yaml, chart/templates/maps-api/configmap.yaml, chart/templates/maps-api/deployment.yaml, chart/templates/router/configmap.yaml, chart/templates/sql-worker/configmap.yaml, chart/templates/sql-worker/deployment.yaml, chart/templates/workspace-api/configmap.yaml, chart/templates/workspace-api/deployment.yaml, chart/templates/workspace-subscriber/configmap.yaml, chart/templates/workspace-subscriber/deployment.yaml, chart/values.yaml, customizations/README.md, customizations/proxy/http/customizations.yaml, customizations/proxy/https/customizations.yaml
Shortcut: https://app.shortcut.com/cartoteam/story/310383/enable-proxy-support-for-selfhosted-helm-chart-and-docker
Add the Chart configuration in case CARTO stack runs behind a HTTP or HTTPS proxy
**Benefits**
Be able to work behind a proxy :)
=> Add support for an external proxy

README.md
Change the link to the Download Customer Package Tool since some users complained it was confusing
=> README: clarify update process

tools/carto-download-customer-package.sh
- Story: https://app.shortcut.com/cartoteam/story/324925/fix-download-customer-package-script-to-be-compatible-with-macos
- Autolink: [sc-324925]
In order for `carto-download-customer-package.sh` to support `getopt` long-options in macOS it would require these actions from customer-side: `gnu-getopt` installation + binary linking.
As the above is invasive and error prone, the proposal is to change the usage of `getopt` binary by `getopts` bash builtin function which is native to GNU-Bash packed in both Linux and Darwin systems.
1. NO customer-side actions required (ge: installing/linking new OS packages)
2. Faster to implement
This change will completely remove the long-options usage from `carto-download-customer-package.sh` and short-options will be the only allowed method to pass …
=> [324925] Fix download customer package script to be compatible with MacOS

tools/README.md
Fix `tools/README.md` after https://github.com/CartoDB/carto-selfhosted-helm/pull/378
**Benefits**
Tailor user documentation
N/A
- complementary change for #324925
=> [324925] correct tools/README.md

tools/README.md, tools/carto-download-customer-package.sh
- Story: https://app.shortcut.com/cartoteam/story/329603/fix-selfhosted-download-customer-package
- Autolink: [sc-329603]
1. Make `carto-download-customer-package.sh` work when CLIENT_ID suffix ends with "`-<numbers>`"
2. Consolidate all actions required for docker/k8s in a single block
3. Add minor improvements for input validations, stdout messages and some functions
4. Abort execution on error providing feedback
- fixes #329603
=> [329603] selfhosted: fix CLIENT_ID with numeric suffix + improvements

chart/templates/_helpers.tpl, chart/templates/workspace-api/deployment.yaml, chart/values.yaml, customizations/README.md, customizations/external_postgresql/customizations.yaml
Shortcut: https://app.shortcut.com/cartoteam/story/338514/allow-nondefault-root-database-and-admin-user-in-selfhosted-init-db-script
The default Postgresql's `postgres` database is hard-coded in the init-db (`workspace-migrator`) script, and so does the default port (5432). We are adding support for a custom root  database and port for this script
=> :elephant: Add support for non-default Postgresql's postgres database and non-default port for self-hosted deployments

chart/values.yaml
Shortcut: https://app.shortcut.com/cartoteam/story/340678/increase-maps-api-memory-and-cpu-until-dynamictilingv1-is-deprecated
**Reason**
We need to increase maps-api resources until dynamicTilingV1 is fully deprecated or we reduce the load generated by featuresToBinary transformation
**Previous research**
https://app.shortcut.com/cartoteam/story/340417/investigate-oom-issues-with-maps-api-in-asia-tenant
=> :bricks: Increase `maps-api` memory from 2500MB to 4096MB

tools/carto-download-customer-package.sh
Ticket: https://app.shortcut.com/cartoteam/story/351227/fix-selfhosted-download-customer-packages
Autolink: [sc-351227]
=> Fix version

chart/templates/workspace-www/configmap.yaml
Shortcut: https://app.shortcut.com/cartoteam/story/347069/generativeai-palm-api-key-request
Related PRs
- https://github.com/CartoDB/cloud-native/pull/13884
=> 📦 Add env vars for Google GenAI

manifests/kots-config.yaml, manifests/kots-helm.yaml
Add Kots config for hight availability settings. From now on we'll be able to define the min/max number of instances for the pods running in k8s.
=> Add Kots config for high availability settings

chart/templates/workspace-subscriber/configmap.yaml
With this change, we'll enable the data synchronizing between a SH installation and our Accounts part. Each time that the workspace subscriber is started, we'll check if there is any pending change to be done.
=> Activate data synchronizing between SH and Accounts

manifests/kots-config.yaml
In other cases, we should leave unsetted
=> set buckets default values only for dev license type

chart/README.md, chart/values.yaml
Shortcut: https://app.shortcut.com/cartoteam/story/392894/increase-memory-reduce-concurrency-for-import-api-cloud-run-instances
_Now the `/v3/imports/preview` endpoint use GDAL to extract schema from imported file. This process consumes huge amount of memory on certain file formats and files with many columns (large single row size).
We are getting `Memory limit of 1024 MiB exceeded with ...... MiB used.` errors, preventing the schema preview on large files._
_`import-api` cloud run instances memory should be increased to 2GB & concurrency reduced to 10._
=> :hammer_and_wrench: Update the the `import-api` memory

manifests/kots-app.yaml, manifests/kots-helm.yaml
The values provided to the `--http-proxy`, `--https-proxy`, and `--no-proxy` flags for the kots install command are now propagated to the Replicated SDK, so there is no need to add them manually.
=> delete old proxy env vars in replicated sdk

chart/README.md, chart/templates/_validators.tpl, chart/templates/accounts-www/configmap.yaml, chart/templates/http-cache/configmap.yaml, chart/templates/import-api/configmap.yaml, chart/templates/import-worker/configmap.yaml, chart/templates/lds-api/configmap.yaml, chart/templates/maps-api/configmap.yaml, chart/templates/sql-worker/configmap.yaml, chart/templates/support-bundle.yaml, chart/templates/workspace-api/configmap.yaml, chart/templates/workspace-subscriber/configmap.yaml, chart/templates/workspace-www/configmap.yaml, chart/values.yaml, manifests/kots-helm.yaml
This PR adds an easier way to enable the debug mode in SH. For installations using Kots, we'll have a checkbox to enable it in the config and we've added a check in the support bundle to notify the user if they've generated a support bundle without enabling the debug mode:
We've also added a validator in the Helm chart to ensure that the customer provides a valid value for the `logLevel`:
```
{"level":"error","ts":"2024-12-12T08:44:30Z","msg":"rewrite directory: failed to write rendered: failed to write helm rendered: failed to template helm chart for rendered dir: failed to run helm install: execution error at (carto/templates/NOTES.txt:113:3): \nVALUES VALIDATION:\nInvalid logLevel: random. Must be one of [info debug error]"}
```
=> Add logLevel option to the Helm chart values

chart/templates/_commonChecks.tpl, chart/templates/preflight.yaml, chart/templates/support-bundle.yaml
Create the support bundle and the preflights secret in both the Kots and the Helm installation by default, and adapted the checks to use existing secrets in the Helm chart deployment. Now we support existing secrets for:
- `cartoSecrets.defaultGoogleServiceAccount`
- `appSecrets.awsAccessKeyId`
- `appSecrets.awsAccessKeySecret`
- `appSecrets.azureStorageAccessKey`
- `appSecrets.googleCloudStorageServiceAccountKey`
- `externalPostgresql`
- `externalRedis`
- `launchDarklySdkKey`
=> Include support bundle & preflight checks in helm installation

.github/actions/publish-release/action.yaml
Story — https://app.shortcut.com/cartoteam/story/452515/get-the-self-hosted-helm-repository-out-of-avid-wavelet-844
Update the self-hosted release process to use the new Helm repository Storage Bucket
Related PRs
- https://github.com/CartoDB/cloud-native/pull/19196
- https://github.com/CartoDB/terraform-aws-prod/pull/311
=> chore(helm): :package: migrate the self-hosted Helm repository

.github/workflows/check-helm-chart-resources.yaml, .github/workflows/lint-codebase.yaml, .github/workflows/release-autotag.yaml
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/470573
- Autolink: [sc-470573]
In order to avoid deprecation and our CI/CD not running because we are using runners deprecated upgrade to the latest version available.
=> Upgrade ubuntu-20.04 to ubuntu-24.04 runner version

chart/templates/litellm/configmap.yaml, chart/templates/litellm/deployment.yaml, chart/values.yaml
Shortcut
- Story:https://app.shortcut.com/cartoteam/story/506249/add-entrypoint-to-litellm-dockerfile?vc_group_by=day&ct_workflow=all&cf_workflow=500193639
- Autolink: [[506249](https://app.shortcut.com/cartoteam/story/506249/add-entrypoint-to-litellm-dockerfile?vc_group_by=day&ct_workflow=all&cf_workflow=500193639)]
To standarize the enviroments we are going to migreate the URL construction from env vars handling in terraform / helm to a Docker entrypoint. 
1. Test entrypoint.sh locally 
2. Test in both environment SaaS & K8s
=> Move url construct to Litellm Docker entrypoint
