CONTRIBUTING.md

Improves considerably how to contribute guidelines
**Benefits**
Others can understand how to participate developing and collaborating.

Fix CONTRIBUTING.md which was incomplete

---

chart/Chart.yaml
chart/templates/accounts-www/deployment.yaml
chart/templates/import-api/deployment.yaml
chart/templates/import-worker/deployment.yaml
chart/templates/lds-api/deployment.yaml
chart/templates/maps-api/deployment.yaml
chart/templates/router/deployment.yaml
chart/templates/workspace-api/deployment.yaml
chart/templates/workspace-subscriber/deployment.yaml
chart/templates/workspace-www/deployment.yaml

In case we are in diagnostic mode, we do not want the init containers to execute.
**Benefits**
- fixes #

fix: :bug: Do not deploy initContainers in diagnosticMode

---

chart/Chart.yaml
chart/README.md
chart/values.yaml

Persistence in Redis is not necessary, according to the CARTO team. This PR disables PVCs in the Redis subchart.
**Benefits**
- fixes #

perf: :zap: Disable persistence in Redis

---

chart/Chart.yaml
chart/templates/accounts-www/deployment.yaml
chart/templates/import-api/deployment.yaml
chart/templates/import-worker/deployment.yaml
chart/templates/lds-api/deployment.yaml
chart/templates/maps-api/deployment.yaml
chart/templates/workspace-api/deployment.yaml
chart/templates/workspace-subscriber/deployment.yaml
chart/templates/workspace-www/deployment.yaml

The tls-secret mount was not only necessary in the router component. Removed from the rest.
**Benefits**
- fixes #

refactor: :fire: Remove unneccesary tls-secret mounts

---

tests/carto.json

Set the last successful commit as source for chart in the verification platform pipeline example
**Benefits**
Verification platform pipeline is updated with the last changes

Set the last successful commit as source for chart

---

.github/workflows/vib.yaml

Change VIB GitHub action reference

Change VIB GitHub action reference

---

.vib/vib-pipeline.json
.vib/vib-platform-verify.json

There are changes into the new DSL, so VIB pipelines need to be updated.
**Benefits**
Easier to understand and to write VIB pipeline

VIB pipelines updated to the latest DSL version

---

chart/templates/accounts-www/configmap.yaml
chart/templates/import-api/configmap.yaml
chart/templates/import-worker/configmap.yaml
chart/templates/lds-api/configmap.yaml
chart/templates/maps-api/configmap.yaml
chart/templates/router/configmap.yaml
chart/templates/workspace-api/configmap.yaml
chart/templates/workspace-subscriber/configmap.yaml
chart/templates/workspace-www/configmap.yaml

- Sorting lines in order to troubleshoot better env var issues

sort lines

---

README.md

Add comments for EKS

---

chart/templates/accounts-www/configmap.yaml
chart/templates/workspace-www/configmap.yaml

Add launchdarkly param to www configmaps

---

README.md

Add steps custom domain

---

README.md
chart/templates/externaldb-secret.yaml
chart/templates/import-api/deployment.yaml

Connect with external cloud postgres and redis

---

.github/workflows/release.yaml
chart/Chart.yaml

- Include versions in Chart.yaml
- Add github action to make release and upload package
**Benefits**
- fixes #

Add github action to make release

---

chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/23dd7d732a86c8d3f5902cb53f1d5acaded57cfb

Update to `1.6.13` release

---

.github/workflows/release.yaml
chart/Chart.yaml

Helm release

---

chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/23dd7d732a86c8d3f5902cb53f1d5acaded57cfb

Update to `1.6.15` release

---

chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/057f0109cc095289856270ba4ac6eb465ed4a5e0

Update to `1.8.1` release

---

chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/42c1001d565d406ed71985823bedf81e403f807c

Update to `1.9.1` release

---

chart/templates/_helpers.tpl
chart/templates/accounts-www/configmap.yaml
chart/templates/accounts-www/secret.yaml
chart/templates/cdn-invalidator-sub/configmap.yaml
chart/templates/cdn-invalidator-sub/deployment.yaml
chart/templates/cdn-invalidator-sub/secret.yaml
chart/templates/google-serviceaccount-secret.yaml
chart/templates/http-cache/deployment.yaml
chart/templates/http-cache/secret.yaml
chart/templates/import-api/configmap.yaml
chart/templates/import-api/secret.yaml
chart/templates/import-worker/configmap.yaml
chart/templates/import-worker/secret.yaml
chart/templates/lds-api/configmap.yaml
chart/templates/lds-api/secret.yaml
chart/templates/maps-api/configmap.yaml
chart/templates/maps-api/secret.yaml
chart/templates/router/configmap.yaml
chart/templates/router/secret.yaml
chart/templates/workspace-api/configmap.yaml
chart/templates/workspace-api/secret.yaml
chart/templates/workspace-subscriber/configmap.yaml
chart/templates/workspace-subscriber/secret.yaml
chart/templates/workspace-www/configmap.yaml
chart/templates/workspace-www/secret.yaml
chart/values.yaml

Refactor carto values and custom client values
Include template for google service account
**Benefits**
- fixes #

Refactor carto values and secrets

---

chart/Chart.lock
chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/0b86007acc848aeb7f88c9d40dce87d3057acc70

Update to `1.11.2` release

---

README.md
chart/README.md
chart/templates/NOTES.txt
chart/templates/_helpers.tpl
customizations/README.md

More improvements to the documentation

Improving documentation

---

.github/workflows/package.yaml
README.md

Add new helm carto repository
**Benefits**
- fixes #

feat(helm): Add new helm carto repository

---

.github/workflows/package.yaml
.vib/vib-platform-verify.json
README.md

Signed-off-by: FraPazGal <fdepaz@vmware.com>
As commented in #65, insufficient resources issues reappeared in #70 with the following logs:
```
Node didn't have enough resource: cpu, requested: 250, used: 7676, capacity: 7910
```
Adding an extra worker node we'll ensure no further resources errors pop up.
**Benefits**
Avoids insufficient resources errors.

Increase VIB worker nodes

---

chart/Chart.lock
chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/bcfc463fa19eee82d2c82ade0a267b214503cdcc

Update to `1.14.11` release

---

.github/workflows/package.yaml
chart/Chart.yaml

change folder bucket name

---

TROUBLESHOOTING.md
chart/templates/NOTES.txt

Improve docu based on feedbacks

---

chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/a87e9c734ce60991f8f55aad80dc710358752f27

Update to `1.17.1` release

---

chart/templates/lds-api/configmap.yaml
chart/templates/workspace-subscriber/configmap.yaml

they are not critical, but traces are "incomplete"

Missing Env vars

---

chart/templates/lds-api/configmap.yaml

- Add Auth0 vars to lds-api config map
**Benefits**
- LDS API is unusable 

fix(lds-api): Add Auth0 vars to lds-api config map

---

chart/templates/_helpers.tpl
chart/templates/externalredis-configmap.yaml
chart/templates/import-api/configmap.yaml
chart/templates/import-api/deployment.yaml
chart/templates/lds-api/configmap.yaml
chart/templates/lds-api/deployment.yaml
chart/templates/maps-api/configmap.yaml
chart/templates/maps-api/deployment.yaml
chart/templates/workspace-api/configmap.yaml
chart/templates/workspace-api/deployment.yaml
chart/templates/workspace-subscriber/configmap.yaml
chart/templates/workspace-subscriber/deployment.yaml

Now the `REDIS_TLS_CA` env var will point to a file rather than having the content of the CA
**Benefits**
- fixes #

Change REDIS_TLS_CA from content to a filepath

---

chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/6496eef4b70588a985b4a5a0e6be8fc4ea166be4

Update to `1.22.1-2022.05.12-5` release

---

chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/1092fdfaef7143b3ccf3fb546f27049fbdd3135a

Update to `1.23.2-2022.5.23` release

---

chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/8bf6ec7511cc379a67f9e5bce6e02f9dbe8ac75f

Update to `1.23.7-2022.6.1-11` release

---

customizations/scale_components/autoscaling.yaml
customizations/scale_components/static.yaml

We agreed on **removing static scale** option for any subscriber, until we can test it properly.

Removing subscribers from static scaling

---

chart/templates/pre-upgrade-check-versions-job.yaml

Update the docker image for the prehooks scripts from the docker registry to our gcp registry.
Change base docker image for prehooks to our registry.
**Benefits**
Avoid docker rate limit errors in download images.
- fixes #

change prehook base image

---

chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/6aa92b4e7d1684d2e067114509972e2edc250faa

Update to `1.24.3-2022.6.6-2` release

---

chart/values.yaml

- Increase maps api container memory for requests and limit
**Benefits**
- Avoid OOM errors
- fixes #

increase maps api container memory

---

.github/workflows/vib.yaml
customizations/resources/minimum.yaml

With this PR we changed from use github secret with the helm customization for running CI to generate dynamically retrieving the required secrets from google secrets.
**Benefits**
More maintainability and ease of upgradeability in the different versions of the Carto packages.
- fixes #

[CI] Create helm customization from gcloud secrets instead of github

---

.github/workflows/vib.yaml

- Add the rest of Cloud providers for testing with VIB
**Benefits**
- Be able to run tests in all cloud platform providers
- fixes #

execute VIB in all cloud platforms

---

chart/README.md
chart/templates/_helpers.tpl
chart/values.yaml

Changes on podSecurityContext and containerSecurityContext default values to aling to non root containers.
**Benefits**
- fixes #

Change defaults security context

---

.vib/vib-platform-verify.json
chart/Chart.lock
chart/Chart.yaml

- https://github.com/CartoDB/cloud-native/commit/d9b689621cd90503bd7fcd1e017a69ffe64bb365

Update to `1.29.3-2022.6.23` release

---

.github/linters/.markdown-lint.yml
customizations/README.md

https://app.shortcut.com/cartoteam/story/239724/carto-selfhosted-docker-readme-revamp

Doc terraform examples

---

README.md
doc/gke/gke-workload-identity.md

- Update workload identity doc with role binding example
- Update main Readme with Helm version prerequisite
**Benefits**
- fixes #

Add doc examples

---

README.md

https://app.shortcut.com/cartoteam/story/219533/give-instructions-to-check-that-all-is-working-fine

add basic post installation checks

---

chart/README.md
chart/templates/NOTES.txt
chart/templates/accounts-www/deployment.yaml
chart/templates/cdn-invalidator-sub/deployment.yaml
chart/templates/http-cache/deployment.yaml
chart/templates/import-api/deployment.yaml
chart/templates/import-worker/deployment.yaml
chart/templates/lds-api/deployment.yaml
chart/templates/maps-api/deployment.yaml
chart/templates/router/deployment.yaml
chart/templates/sql-worker/deployment.yaml
chart/templates/workspace-api/deployment.yaml
chart/templates/workspace-subscriber/deployment.yaml
chart/templates/workspace-www/deployment.yaml
chart/values.yaml

Values.<service>.[configuration|secretConfiguration] y Values.global.[commonConfiguration|secretConfiguration]
These values are not used and are here for legacy configuration (the time when we provide a HEREDOC with all values). I will remove it to avoid errors
**Benefits**
Avoid errors
Only changed template is NOTES.txt, tested (but not in all scenarios)
https://app.shortcut.com/cartoteam/story/219540/recheck-secret-internal-configuration
- fixes #

remove unused values

---

.github/linters/.markdown-lint.yml
chart/templates/workspace-subscriber/configmap.yaml
chart/templates/workspace-subscriber/deployment.yaml
chart/templates/workspace-subscriber/secret.yaml

- Add missing env vars to workspace subscriber
- Disable lint rule - Allow start file with h2 title in Changelog
**Benefits**
- fixes #

Add missing workspace vars

---

chart/README.md
chart/values.yaml

- Declare default value for `workspaceImportsPublic`
**Benefits**
- fixes #

Add default value for workspaceImportsPublic

---

chart/templates/pre-upgrade-check-versions-job.yaml

Missed configuration in upgrade check to use image pull secrets
**Benefits**
- fixes #

add image pull secrets conf to upgrade check

---

chart/templates/workspace-api/deployment.yaml

adding resources configuratiopn to workspace migrations init container
**Benefits**
- fixes #

add resources to ws migration

---

customizations/README.md

Typo in parameter indentation

---

.github/workflows/lint-codebase.yaml
customizations/README.md
customizations/external_postgresql/cloudsql/customizations.yaml

Add a customizations example to conect to Cloud SQL postgresql through Cloud SQL Auth Proxy
**Benefits**
- fixes #

CloudSQL Auth Proxy example

---

chart/templates/carto-common-service-account.yaml
customizations/README.md
customizations/ingress/gke/config.yaml

- Update ingress doc and steps
**Benefits**
- fixes #

Update ingress doc

---

customizations/README.md

Fix `customizations/README.md` typo
Better understand the documentation
There is no limitation
- fixes #

Fix tabulation typo

---

customizations/ingress/gke/config.yaml

- Add GCE ingress class in example config file to avoid errors in GKE
**Benefits**
- fixes #

Add gce ingress class in example config file

---

chart/templates/lds-api/configmap.yaml

- Add missing env vars to lds api
**Benefits**
- fixes #

Add pubsub missing vars to lds api

---

CHANGELOG.md
chart/Chart.lock
chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/d2419649253784b8fd753378404596ef6eb6e88e

Update to `1.39.14-2022.8.11-8` release

---

customizations/README.md
customizations/ingress/gke/custom_cert_config.yaml
customizations/ingress/gke/gcp_managed_cert_config.yaml

- Doc: Refactor Readme -> How to access to Carto from external network
**Benefits**
- fixes #

Update selfhosted lb docs

---

TROUBLESHOOTING.md
customizations/README.md

- Add Ingress Troubleshooting
**Benefits**
- fixes #

Add ingress certs doc

---

CHANGELOG.md
chart/Chart.lock
chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/fe7299c7f5a90864a4f962963fdca6dda8793e88

Update to `1.40.1-2022.8.19-1` release

---

CHANGELOG.md
chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/b3e41ca37e043708c255a0208d44873c6be98ffc

Update to `1.41.1-2022.9.2` release

---

CHANGELOG.md
chart/Chart.lock
chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/1b560848b6267bc5abcb2d31ba94039f1547944e

Update to `1.42.1-2022.9.16` release

---

CHANGELOG.md
chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/da4038fe4129f17836df75bf3d0829935428cba5

Update to `1.42.3-2022.9.19` release

---

CHANGELOG.md
chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/5f89fa6722fc418812f2f6e329763227691fec6a

Update to `1.42.5-2022.9.20` release

---

chart/templates/workspace-api/configmap.yaml

- Add new var in workspace api for tenant bus
**Benefits**
- fixes #

Add new var in workspace-api

---

chart/templates/workspace-api/configmap.yaml
chart/templates/workspace-subscriber/configmap.yaml

- Add vars to workspace components
**Benefits**
- fixes #

set vars to workspace components

---

CHANGELOG.md
chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/86084249fba85a2cd341cb68b449d23c212c5771

Update to `1.42.10-2022.9.28` release

---

CHANGELOG.md
chart/Chart.lock
chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/65bf8ff780cbd1c14419dca292a1208bd888bc51

Update to `1.42.13-2022.10.7-1` release

---

chart/templates/workspace-subscriber/configmap.yaml

Add selfhosted WORKSPACE_PUBSUB_TENANT_BUS_SUBSCRIPTION env var
**Benefits**
- fixes #

Add WORKSPACE_PUBSUB_TENANT_BUS_SUBSCRIPTION var

---

customizations/README.md

https://app.shortcut.com/cartoteam/story/265273/test-and-document-new-redshift-imports-for-selfhosted

add redshift imports information

---

README.md
tools/README.md
tools/carto-download-customer-package.sh

First version of the `carto-download-customer-package.sh` tool
```
$ ./carto-download-customer-package.sh -d ~/CartoDB/util/selfhosted/qa-onprem/k8s/ -s dockerActivated service account credentials for: [serv-onp-qa-onprem@carto-tnt-onp-qa-onprem.iam.gserviceaccount.com]
Copying gs://carto-tnt-onp-qa-onprem-client-storage/customer-package/carto-selfhosted-docker-customer-package-qa-onprem-2022-10-18.zip...
/ [1 files][  3.5 KiB/  3.5 KiB]                                                
Operation completed over 1 objects/3.5 KiB.                                      
##############################################################
Current selfhosted version in [carto-values.yaml]: 2022.10.7-1
Latest selfhosted version downloaded: 2022-10-18
Downloaded file: …
```

Adding download customer package tool for clients

---

.github/workflows/vib.yaml

In the next release, we're going to add a new private dependency not required for the e2e-test so we should avoid the installation on VIB.
**Benefits**
Avoid grant more permission to a private package not required for e2e
- fixes #

Avoid the installation of workflows-engine for E2E

---

customizations/README.md

https://github.com/CartoDB/carto-selfhosted/pull/244

clarify connection pool

---

CHANGELOG.md
chart/Chart.lock
chart/Chart.yaml
chart/templates/sql-worker/deployment.yaml
chart/templates/sql-worker/secret.yaml
customizations/README.md

https://github.com/CartoDB/cloud-native/commit/7e0b9de9048a95491d8feec1ab955eb354aa3c54

Update to `1.43.7-2022.12.14` release

---

CHANGELOG.md
chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/68a2916bc91dbd53540b7da91b985894c78b5087

Update to `1.43.9-2023.1.3` release

---

chart/README.md
chart/templates/cdn-invalidator-sub/configmap.yaml
chart/templates/import-api/configmap.yaml
chart/templates/import-worker/configmap.yaml
chart/templates/lds-api/configmap.yaml
chart/templates/maps-api/configmap.yaml
chart/templates/sql-worker/configmap.yaml
chart/templates/workspace-api/configmap.yaml
chart/templates/workspace-subscriber/configmap.yaml
chart/values.yaml

- Disable stack traces in responses
**Benefits**
- fixes #

disable ErrorResponseStackTrace by default

---

CHANGELOG.md
chart/Chart.yaml
chart/templates/maps-api/configmap.yaml
chart/templates/maps-api/deployment.yaml
chart/templates/maps-api/secret.yaml

https://github.com/CartoDB/cloud-native/commit/aa5a204f93e1d2d9cbd7bada7b81e5752c214937

Update to `1.43.12-2023.2.2` release

---

customizations/README.md
customizations/workload_identity_connection/customizations.yaml

- Add documentation for Workload Identity Connection feature

add workload identity bigquery documentation

---

.github/workflows/lint-codebase.yaml
customizations/README.md

- Add doc to explain how to disable TrackJS in www components
**Benefits**
- fixes #

how to disable trackjs www

---

chart/templates/_helpers.tpl
chart/templates/workspace-www/deployment.yaml
chart/templates/workspace-www/secret.yaml

fix google maps api key env var name

---

chart/templates/import-api/deployment.yaml
chart/templates/import-api/secret.yaml
chart/templates/import-worker/deployment.yaml
chart/templates/import-worker/secret.yaml

- Add `IMPORT_JWT_SECRET` to `import-worker` service.

add import jwt secret to import-worker

---

.github/workflows/lint-codebase.yaml
.github/workflows/release-autotag.yaml

**Benefits**
Autotag repository when a new release is created
- fixes #

Update autotag workflow

---

.github/workflows/release-automerge.yaml

- Set squash merge method in automerge release
**Benefits**
Be able to auto-merge releases
- fixes #

set squash merge

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/fa736cbf7a27ada3d43b28c1e5608cccd73e7ad3

:rocket: Update to `1.44.13-2098.12.12`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/ba3d1f165bd6dfbaca6299122d9b80f9a84eb7df

:rocket: Update to `1.44.18-2097.11.11`

---

chart/Chart.yaml

Delete testing releases

---

.github/workflows/lint-codebase.yaml
chart/README.md
chart/templates/_helpers.tpl
chart/templates/cdn-invalidator-sub/configmap.yaml
chart/templates/import-api/configmap.yaml
chart/templates/import-worker/configmap.yaml
chart/templates/lds-api/configmap.yaml
chart/templates/maps-api/configmap.yaml
chart/templates/router/configmap.yaml
chart/templates/sql-worker/configmap.yaml
chart/templates/workspace-api/configmap.yaml
chart/templates/workspace-subscriber/configmap.yaml
chart/values.yaml

dynamic memory allocation to containers

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/11c3f541709b36630d3afc427dc26726f028fb16

:rocket: Update to `1.44.26-2023.3.31-rc.1`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/cee9ce1dfd1e483320500a889362d8bdeb641186

:rocket: Update to `1.44.32-2023.3.31-rc.2`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/e73a8b01285d5cc1de75c05beff4cd62521ca25d

:rocket: Update to `1.44.34-2023.3.31`

---

chart/templates/accounts-www/pdb.yaml
chart/templates/cdn-invalidator-sub/pdb.yaml
chart/templates/http-cache/pdb.yaml
chart/templates/import-api/pdb.yaml
chart/templates/import-worker/pdb.yaml
chart/templates/lds-api/pdb.yaml
chart/templates/maps-api/pdb.yaml
chart/templates/notifier/pdb.yaml
chart/templates/router/pdb.yaml
chart/templates/sql-worker/pdb.yaml
chart/templates/workspace-api/pdb.yaml
chart/templates/workspace-subscriber/pdb.yaml
chart/templates/workspace-www/pdb.yaml
chart/values.yaml
customizations/README.md
customizations/pod_disruption_budget/customizations.yaml

support for podDisruptionBudget

---

tools/carto-support-tool.sh

Obtain nodes information with `carto-suppor-tool.sh`
**Benefits**
- fixes #

Update `carto-support-tool.sh` with support for nodes

---

chart/templates/workspace-www/configmap.yaml
chart/values.yaml

disable exports by default

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/3a3be18ad6a109cc09e535c024c1fcb1cb4b6424

:rocket: Update to `1.45.11-2023.5.12-rc.1`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/f4dc29273dc9427c45c1865c058e81799fc9696f

:rocket: Update to `1.45.17-2023.5.12`

---

chart/templates/accounts-www/configmap.yaml
chart/templates/workspace-www/configmap.yaml
chart/values.yaml
customizations/README.md

Disabling the TrackJS now will be configured via `appCartoConfig.enableTrackJS` parameter rather than directly via env vars
**Benefits**
- fixes #

Refactor customization for disabling TrackJS

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/22ed3e8722415c2790d04200e440acccefef10aa

:rocket: Update to `1.45.27-2023.6.16-rc.2`

---

customizations/README.md

Shortcut: https://app.shortcut.com/cartoteam/story/324136/fix-indosat-s-self-hosted-cors-issue
If we use custom buckets we need to add CORS policies to the Client and Thumbnails buckets, the Import bucket doesn't need to be modified
**Benefits**
- fixes #

Clarify docs about using custom buckets

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/a299141812173e35bbb4c1b7440b08b70c86bcef

:rocket: Update to `1.45.30-2023.6.16-rc.3`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/0ca50eb731c2efa8a8efce10018a6939bec35bb5

:rocket: Update to `1.45.34-2023.6.16-rc.4`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/e866a1c852ef8a82437cdf8ffef0fe5aa363f205

:rocket: Update to `1.45.36-2023.6.16-rc.5`

---

chart/templates/accounts-www/pdb.yaml
chart/templates/cdn-invalidator-sub/pdb.yaml
chart/templates/http-cache/pdb.yaml
chart/templates/import-api/pdb.yaml
chart/templates/import-worker/pdb.yaml
chart/templates/lds-api/pdb.yaml
chart/templates/maps-api/pdb.yaml
chart/templates/notifier/pdb.yaml
chart/templates/router/pdb.yaml
chart/templates/sql-worker/pdb.yaml
chart/templates/workspace-api/pdb.yaml
chart/templates/workspace-subscriber/pdb.yaml
chart/templates/workspace-www/pdb.yaml
chart/values.yaml

Fix deprecated kubernetes Policy API version
`policy/v1beta1 PodDisruptionBudget Deprecated in v1.21+, unavailable in v1.25+`
**Benefits**
- fixes #

parametrize kubernetes policy api version

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/b4dd0a634c653ec5fa6fe1fbb664dfbce0c85340

:rocket: Update to `1.45.40-2023.6.16-rc.6`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/de8c0a44f04f2b4d759041d05b4e2ab509895817

:rocket: Update to `1.45.42-2023.6.16`

---

README.md

- Update whitelisted domains link.
https://app.shortcut.com/cartoteam/story/322561/selfhosted-release-june-2023-6-16

Updating whitelisted domain list

---

chart/templates/router/configmap.yaml
chart/values.yaml

https://app.shortcut.com/cartoteam/story/324912/parametrize-selfhosted-nginx-config-vars
**Benefits**
- fixes #

Parametrize router nginx

---

chart/README.md
chart/templates/import-api/configmap.yaml
chart/templates/import-worker/configmap.yaml
chart/templates/sql-worker/deployment.yaml
chart/values.yaml

Reorder configmaps and secrets

---

chart/Chart.yaml

:tada: Bump selfhosted version to `2023.7.11-rc.1`

---

chart/templates/accounts-www/configmap.yaml
chart/templates/cdn-invalidator-sub/configmap.yaml
chart/templates/import-api/configmap.yaml
chart/templates/import-worker/configmap.yaml
chart/templates/lds-api/configmap.yaml
chart/templates/maps-api/configmap.yaml
chart/templates/notifier/configmap.yaml
chart/templates/sql-worker/configmap.yaml

add CARTO_SELFHOSTED_VERSION env var

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/d140015b56088898a875f45fafb409d11bdfcc1e

:rocket: Update to `1.46.8-2023.7.17-rc.4`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/85a82debe59c3b459ded972a76e469dde224414f

:rocket: Update to `1.46.12-2023.7.17`

---

customizations/README.md
customizations/ingress/gke/custom_cert_config.yaml
customizations/ingress/gke/gcp_managed_cert_config.yaml

add ingress ssl policy documentation

---

chart/values.yaml

Increase `import-worker` memory limit from 4GB to 8GB and from 1000CPU to 2000CPU
**Benefits**
Avoid possible crashes or endless operations when trying to import QGIS files with complex geometries
- fixes #

🧱 Increase `import-worker` memory limit from 4GB to 8GB and CPU from 1000M to 2000M

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/9b30e9ae52878d202929c8e602998bb8d89a8a20

:rocket: Update to `1.46.3-rc.2-2023.9.20-rc.1`

---

semver.yaml

refactor semver file

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/16e1e415e7786579271af9d1c1b9ade5ee4491a6

:rocket: Update to `1.131.1-2023.9.20-rc.3`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/70a7df14079079cdf7a2e92a56a6a59807443163

:rocket: Update to `1.52.1-2023.9.20-rc.4`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/d999d07a01f63aa1af9ab6862de73a509dfe13d0

:rocket: Update to `1.53.1-2023.9.20-rc.5`

---

README.md

Update links to doc

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/98a4a3b4cb09f3acd8e357ebb2738263de25c7cc

:rocket: Update to `1.55.2-2023.9.20-rc.6`

---

chart/templates/workspace-subscriber/configmap.yaml

Add compute pubsub data-updates subscription to workspace-subs

---

doc/customizations-access-to-carto-from-outside-the-cluster.md
doc/customizations-components-scaling.md
doc/customizations-configure-an-external-proxy.md

Fix links (customizations-examples)

Fix documentation links

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/b3ef4468caf836ac2ba13d725c00d07d344779d7

:rocket: Update to `1.57.2-2023.9.20-rc.7`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/e34268f8d9a72ae7407ad3103e198945ae8d147b

:rocket: Update to `1.58.3-2023.9.20-rc.8`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/f9aa2c4be3d955178ab62227f851da4390a71a74

:rocket: Update to `1.59.1-2023.9.20-rc.9`

---

chart/templates/accounts-www/configmap.yaml
chart/templates/workspace-www/configmap.yaml
chart/values.yaml

Add a new config value to configure the organization ID when setting up the SSO in the app

Add config value for SSO organization ID

---

chart/templates/workspace-api/configmap.yaml
chart/values.yaml

Add new config values to inject the AT location inside new connections in Workspace API

Add env variables in Workspace API for AT location

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/6bbe825fa13a6759d3f896fafbf0c921fdfd9d13

:rocket: Update to `1.61.4-2023.10.25-rc.1`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/50ff7057566bdde0d51443fb793afd4c45e4c6c6

:rocket: Update to `1.62.1-2023.10.25-rc.2`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/6dfdbe05a445f63bc6ddf090062d6ccaaf744b50

:rocket: Update to `1.63.1-2023.10.25-rc.3`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/59fa23e955518d141124d23e811854e9c36f8b08

:rocket: Update to `1.64.1-2023.10.25-rc.4`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/6903ec74c0ddfec681d34074e824feb78aab1c33

:rocket: Update to `1.65.1-2023.10.25`

---

chart/templates/maps-api/configmap.yaml
chart/templates/sql-worker/configmap.yaml
chart/templates/workspace-api/configmap.yaml
chart/values.yaml

Add a new variable into the appConfigValues to support exports from Workflows.

Add workspaceExportsBucket to appConfigValues

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/45d897e8323983f0e5cf39dd03283a406654daf4

:rocket: Update to `1.66.4-2023.11.29-rc.6`

---

chart/Chart.yaml

https://github.com/CartoDB/cloud-native/commit/67f34304ebf9b47c98b81afc4c36363b93bbab87

:rocket: Update to `1.69.2-2023.11.29`

---

.github/workflows/lint-codebase.yaml

Uncomment step to check HELM documentation when performing changes to prevent having outdated HELM documentation.

Uncomment step to check HELM documentation when performing changes

---

manifests/kots-config.yaml

Fix email on the config

---

manifests/kots-config.yaml
manifests/kots-helm.yaml

Some adjustments to our configs in order to start testing

Config adjustments

---

chart/README.md
chart/templates/_commonChecks.tpl
chart/templates/_helpers.tpl
chart/templates/preflight.yaml
chart/values.yaml

- Add workspace-db preflights with the `tenant-requirements-checker` component

Add tenant requirements checker component

---

chart/templates/support-bundle.yaml
manifests/kots-config.yaml
manifests/kots-helm.yaml

Second bunch of minor fixes

---

manifests/embbeded-cluster.yaml
manifests/kots-config.yaml

[WIP] Refine Kots

---

manifests/kots-config.yaml

Fix Openshift (and other unsupported platform) accessToCarto section

---

manifests/kots-helm.yaml

- Update kots-kelm after selfhosted release published
**Benefits**
- fixes #

upgrade kots-helm after release

---

manifests/kots-config.yaml
manifests/kots-helm.yaml

Allow to define cache resources when enabling HA

---

chart/templates/gateway/gateway-api.yaml
chart/templates/gateway/health-check-policy.yaml

Create gke api gateway health checks

---

chart/templates/_commonChecks.tpl
manifests/kots-app.yaml
manifests/kots-config.yaml
manifests/kots-helm.yaml

enable supportMinimalRBACPrivileges and cluster preflights

---

chart/templates/_commonChecks.tpl
manifests/kots-config.yaml
manifests/kots-helm.yaml

update workload identity config

---

manifests/kots-helm.yaml

update replicated sdk to be able to use proxy

---

chart/templates/maps-api/configmap.yaml
chart/templates/workspace-api/configmap.yaml
chart/templates/workspace-subscriber/configmap.yaml

Change PubSub

---

manifests/kots-helm.yaml

Prepare for code freeze release 2024.08.14 . Delete temporal patched images

Delete patched images

---

chart/templates/_helpers.tpl
chart/templates/cdn-invalidator-sub/deployment.yaml
chart/templates/import-api/deployment.yaml
chart/templates/import-worker/deployment.yaml
chart/templates/lds-api/deployment.yaml
chart/templates/maps-api/deployment.yaml
chart/templates/notifier/deployment.yaml
chart/templates/sql-worker/deployment.yaml
chart/templates/workspace-api/deployment.yaml
chart/templates/workspace-subscriber/deployment.yaml

recreate components when posgres and redis password changes
